const ToolTipContent = {
  changePassword: "Change Password",
  logout: "Logout",
  trialDate: "Trial Date",
  deliveryDate: "Delivery Date",
  coustomerName: "Full Name",
  mobileNumber: "Mobile Number",
  emailAddress: "Email Address",
  address: "Address",
  customerType: "Customer Type",
  selectBOD: "Select Birth of Date",
  selectAnniDate: "Select Anniversary Date",
  selectIndividual: "Select Individual Corporate",
  uploadCustomerImage: "Upload Customer Image",
  editOrderDetails: "Edit Order Details",
  orderDate: "Order Date",
  printInvoice: "Print Invoice",
  emailInvoice: "Email Invoice",
  orderAction: "Other Action",
  editOrder: "Edit Order",
  addNewOrder: "Add New Item",
  removeOrder: "Remove Order Details",
  showBasicAmountDetail: "Click to Show Basic Amount Details",
  dublicateItem: "Dublicate Item",
  imageDetail: " Click to Open Images Details",
  backToCustomer: "Back to Seach Customer Modal",
  totalBalance: "Total Balance",
  LastOrderNo: "Last Order Number",
  LastOrderDate: "Last Order Date",
  customerProfileImage: "Customer Profile Image",
  searchCustomer: "Search Customer",
  editCustomerDetail: "Edit Customer Details",
  closeModel: "Close Modal",
  saleType: "Sale Type",
  orderType: "Order Type",
  priority: "Priority",
  designer: "Designer",
  master: "Master",
  
  orderNo: "Order Number",
  poDate: "PO Date",
  poNo: "PO Number",
  enterMakingAmount: "Please Enter Making Amount",
  enterAccessoriesAmount: "Please Enter Accessories Amount",
  enterFabricAmount: "Please Enter Fabric Amount",
  enterDiscount: "Please Enter Discount",
  taxableAmount: "Taxable Amount",
  taxAmount: "Please Add Tax Amount",
  
};

export default ToolTipContent;
